# Generated by Django 5.0.2 on 2024-03-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_faculty_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty_Profile',
        ),
    ]
