# Generated by Django 5.0.2 on 2024-03-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_faculty_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=1500)),
                ('experience', models.TextField(max_length=1500)),
                ('picture', models.ImageField(upload_to='profile_pictures/')),
            ],
        ),
    ]
