# Generated by Django 5.0.2 on 2024-03-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_faculty_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='Image not found', upload_to='logo_images/')),
                ('college_image', models.ImageField(default='Image not found', upload_to='college_images/')),
                ('description', models.TextField(max_length=1500)),
                ('location', models.TextField(max_length=1000)),
                ('established_date', models.DateField()),
                ('website', models.URLField()),
                ('student_population', models.PositiveIntegerField()),
                ('faculty_population', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('qualification', models.TextField(max_length=1000)),
                ('additional_skills', models.TextField(max_length=1000)),
                ('experience_years', models.IntegerField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.college_profile')),
            ],
        ),
    ]
