# Generated by Django 5.0.2 on 2024-04-04 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_college_profile_avtar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_profile',
            name='college_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='college_images'),
        ),
    ]
