# Generated by Django 5.0.2 on 2024-04-04 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_college_profile_college_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_profile',
            name='college_image',
        ),
        migrations.AddField(
            model_name='college_profile',
            name='images',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
