# Generated by Django 5.0.2 on 2024-04-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_college_profile_college_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_profile',
            old_name='images',
            new_name='college_image',
        ),
    ]
