# Generated by Django 5.0.2 on 2024-04-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_images_college_profile_college_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_profile',
            old_name='college_image',
            new_name='images',
        ),
    ]
