# Generated by Django 5.0.2 on 2024-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_college_image_college_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_profile',
            name='images',
            field=models.ImageField(default='Image not found', upload_to='college_images/'),
        ),
    ]
