# Generated by Django 5.0.2 on 2024-04-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_college_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_profile',
            old_name='picture',
            new_name='avtar',
        ),
    ]
