# Generated by Django 5.0.2 on 2024-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_picture_faculty_profile_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='avtar',
            field=models.ImageField(default='profile pic not found', upload_to='profile_pictures/'),
        ),
    ]
