# Generated by Django 5.0.2 on 2024-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_faculty_profile_avtar'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_profile',
            name='affiliated_by',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='college_profile',
            name='college_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='college_profile',
            name='college_type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('Both', 'Both'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='about',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='qualification',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
