# Generated by Django 5.0.2 on 2024-04-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_college_profile_affiliated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_profile',
            name='affiliated_by',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college_profile',
            name='college_code',
            field=models.CharField(max_length=50),
        ),
    ]
