# Generated by Django 5.0.2 on 2024-04-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_collegepasswordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegepasswordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.college'),
        ),
    ]
