# Generated by Django 5.0.2 on 2024-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_college_password_alter_college_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
