# Generated by Django 5.0.2 on 2024-04-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_college_username_alter_faculty_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject_Teacher',
        ),
    ]
