# Generated by Django 5.0.2 on 2024-04-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_college_username_alter_faculty_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='college_profile',
            name='college',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.college'),
        ),
        migrations.DeleteModel(
            name='Subject_Teacher',
        ),
    ]
