# Generated by Django 5.0.2 on 2024-04-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_college_profile_id_college_profile_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='faculty',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.faculty'),
        ),
    ]
