# Generated by Django 5.0.2 on 2024-04-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_faculty_profile_id_faculty_profile_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='college_profile',
            name='college',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.college'),
        ),
    ]
