# Generated by Django 5.0.2 on 2024-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_college_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
