# Generated by Django 5.0.2 on 2024-04-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_college_profile_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='college',
            new_name='college_profile',
        ),
    ]
