# Generated by Django 5.0.2 on 2024-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_profile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
