# Generated by Django 5.0.2 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_college_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
