# Generated by Django 5.0.2 on 2024-04-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_faculty_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='additional_information',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(default='', max_length=500),
        ),
    ]
