# Generated by Django 5.0.2 on 2024-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_jobpost_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
