# Generated by Django 5.0.2 on 2024-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_college_failed_login_attempts_college_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
